-- AlterTable
ALTER TABLE "User" ADD COLUMN "gamesPlayed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "goals" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "assists" INTEGER NOT NULL DEFAULT 0;
