import footballImg from './assets/football.avif'
import basketballImg from './assets/basketboll.png'
import tennisImg from './assets/tennis.avif'
import tableTennisImg from './assets/table-tennis.avif'
import volleyballImg from './assets/voleyball.avif'

export const SPORTS = [
  {
    id: 'football',
    name: 'Futbol',
    icon: '⚽',
    players: 842,
    teams: 124,
    games: 67,
    leagues: 18,
    image: footballImg,
    color: '#22c55e',
  },

  {
    id: 'tennis',
    name: 'Tennis',
    icon: '🎾',
    players: 389,
    teams: 0,
    games: 218,
    leagues: 9,
    image: tennisImg,
    color: '#eab308',
  },
  {
    id: 'table-tennis',
    name: 'Stolüstü Tennis',
    icon: '🏓',
    players: 276,
    teams: 0,
    games: 341,
    leagues: 7,
    image: tableTennisImg,
    color: '#3b82f6',
  },
  {
    id: 'volleyball',
    name: 'Voleybol',
    icon: '🏐',
    players: 312,
    teams: 54,
    games: 29,
    leagues: 6,
    image: volleyballImg,
    color: '#a855f7',
  },
  {
    id: 'basketball',
    name: 'Basketbol',
    icon: '🏀',
    players: 531,
    teams: 76,
    games: 42,
    leagues: 11,
    image: basketballImg,
    color: '#f97316',
  },
]

export const SPORTS1 = [
  {
    id: 'football',
    name: 'Futbol',
    icon: '⚽',
    description: 'Komandanı qur, rəqiblər tap və yerli liqalarda mübarizə apar.',
    status: 'Ən populyar',
    teamSize: '6v6 — 11v11',
    players: 312,
    teams: 54,
    leagues: 6,
    color: '#22c55e',
    image: footballImg,
  },
  {
    id: 'tennis',
    name: 'Tennis',
    icon: '🎾',
    description: 'Səviyyənə uyğun rəqib tap və fərdi matçlarda gücünü göstər.',
    status: 'Aktiv',
    teamSize: '1v1 — 2v2',
    players: 312,
    teams: 54,
    leagues: 6,
    color: '#eab308',
    image: tennisImg,
  },
  {
    id: 'table-tennis',
    name: 'Stolüstü Tennis',
    icon: '🏓',
    description: 'Rəqibini tap, sürətli matçlara qoşul və reytinqdə yüksəl.',
    status: 'Aktiv',
    teamSize: '1v1 — 2v2',
    players: 312,
    teams: 54,
    leagues: 6,
    color: '#3b82f6',
    image: tableTennisImg,
  },
  {
    id: 'volleyball',
    name: 'Voleybol',
    icon: '🏐',
    description: 'Komanda yığ, oyun təşkil et və turnirlərdə iştirak et.',
    status: 'Yeni',
    teamSize: '4v4 — 6v6',
    players: 312,
    teams: 54,
    leagues: 6,
    color: '#a855f7',
    image: volleyballImg,
  },
  {
    id: 'basketball',
    name: 'Basketbol',
    icon: '🏀',
    description: 'Komanda yarat, meydançaya çıx və digər komandalarla yarış.',
    status: 'Populyar',
    teamSize: '3v3 — 5v5',
    players: 312,
    teams: 54,
    leagues: 6,
    color: '#f97316',
    image: basketballImg,
  },
]



